server:
  port: 8762
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 500
        min-idle: 0
  datasource:
    url: jdbc:mysql://218.59.144.252:3306/db360?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: 56360a
    password: Zz123123
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  freemarker:
    cache: false
    charset: UTF-8
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    allow-session-override: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.mr.securitydemo.dto
